export MLFLOW_EXPERIMENT_NAME="salary_estimator";
export MLFLOW_TRACKING_URI="MLFLOW_TRACKING_URI";
export AWS_ACCESS_KEY_ID="AWS_ACCESS_KEY_ID";
export AWS_SECRET_ACCESS_KEY="AWS_SECRET_ACCESS_KEY";
export BACKEND_STORE_URI="BACKEND_STORE_URI";
export ARTIFACT_ROOT="ARTIFACT_ROOT";